branches:
  only:
    - master
language: node_js
node_js:
  - "10"
env:
  - GH_USER=autofoolip GH_EMAIL=auto@foolip.org
install:
  - npm install
  - git clone --single-branch https://github.com/web-platform-tests/wpt.git
  - cd wpt
  - git remote add fork https://$GH_USER:$GH_TOKEN@github.com/$GH_USER/wpt.git
  - git fetch -q fork
  - git push -q fork master
  - git config user.name $GH_USER
  - git config user.email $GH_EMAIL
  - cd ..
script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      node wpt-sync/sync.js --wpt-dir wpt --build-url https://travis-ci.com/w3c/webref/builds/$TRAVIS_BUILD_ID
    else
      node wpt-sync/sync.js --wpt-dir wpt --dry-run
    fi
