# Runs whenever a push to the default branch updates the package.json file
# of the @webref/idl package. The job publishes a new @webref/idl package to
# npm and creates a new @webref/idl release on GitHub.
#
# The job will not do anything if the version number in package.json does not
# differ from the one published on npm.

name: Create and publish new @webref/idl release

on:
  push:
    paths:
      - 'packages/idl/package.json'  
    branches:
      - master
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Checkout webref
      uses: actions/checkout@v2

    - name: Prepare new release
      run: |
        npm ci
        npm run prepare

    - name: Test new release
      run: npm test

    - name: Publish npm package
      id: publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/idl/package.json
        access: public

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: steps.publish.outputs.type != 'none'
      with:
        name: '@webref/idl@${{ steps.publish.outputs.version }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
